Team Avengers/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Team Avengers/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Practitioner_End_Date__c</fullName>
        <label>Practitioner End Date on Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Practitioner_Start_Date__c</fullName>
        <label>Practitioner Start Date on Project</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Practitioner_Swap__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Practitioner Swap</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Practitioners</relationshipLabel>
        <relationshipName>Practitioners</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Team Avengers/src/classes/MyController.cls
public class MyController 
{	
    public MyController(ApexPages.StandardSetController controller) {
        prac1= new Contact();
        prac2= new Contact();
       	Id profileId=userinfo.getProfileId();
         //Id profileId = ApexPages.currentPage().getParameters().get('Id');
String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
system.debug('ProfileName'+profileName);
        if (ProfileName !='Service Line Leader')
{
	disabled=true;
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Option Disabled'));
    
} 
        else{
            disabled=false;
        }
        
        
    }

    public boolean disabled {get;set;}
    public Contact prac1{get; set;}
    public Contact prac2{get; set;}
    
    
    public PageReference swapPrac()
    {
        try{
            Contact c1= [select Account.Project_Start_Date__c,Account.Project_End_Date__c,AccountId,Id,Practitioner_Start_Date__c,Practitioner_End_Date__c from Contact where Id=:prac1.Practitioner_Swap__c];
            Contact c2 =[select Account.Project_Start_Date__c,Account.Project_End_Date__c,AccountId,Id,Practitioner_Start_Date__c,Practitioner_End_Date__c from Contact where Id=:prac2.Practitioner_Swap__c];
            system.debug('ananya');
            
             Date t1= c1.Account.Project_Start_Date__c;
            c1.Account.Project_Start_Date__c=c2.Account.Project_Start_Date__c;
            c2.Account.Project_Start_Date__c=t1;
            
            Date t2= c1.Account.Project_End_Date__c;
            c1.Account.Project_End_Date__c=c2.Account.Project_End_Date__c;
            c2.Account.Project_End_Date__c=t2;
            system.debug('ananya');
            Date tmp1=c1.Practitioner_Start_Date__c;
            c1.Practitioner_Start_Date__c=c2.Practitioner_Start_Date__c;
            c2.Practitioner_Start_Date__c=tmp1;
            system.debug('ananya');
            
            Date tmp2=c1.Practitioner_End_Date__c;
            c1.Practitioner_End_Date__c=c2.Practitioner_End_Date__c;
            c2.Practitioner_End_Date__c=tmp2;
            
           
            system.debug('ananya');
           
            String tmpStr=c1.AccountId;
            c1.AccountId=c2.AccountId;
            c2.AccountId=tmpStr;
           
            
            system.debug('prac1'+prac1);
            system.debug('prac2'+prac2);
            update c1;
            update c2;
            system.debug('hello');
            //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'swap success'));
            PageReference pageRef = new PageReference('https://ap15.lightning.force.com/lightning/o/Contact/list?filterName=00B2v00000EeolBEAR');
			pageRef.setRedirect(true);
            return pageRef;
            
        }
        catch(Exception e) {
           system.debug('I dont want to come here' +e);
            return null;
        }
        }
    }