Team Avengers/src/objects/PTO_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_status__c</fullName>
        <label>Approval status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>FInal rejection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_PTO_End_Date__c</fullName>
        <label>Last PTO End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PTO_End_Date__c</fullName>
        <label>PTO End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PTO_start_date__c</fullName>
        <label>PTO start date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>PTO Request</label>
    <nameField>
        <label>PTO Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PTO Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Team Avengers/src/classes/Trigger_testclass.cls
@isTest
private class Trigger_testclass {
    static testmethod void myTest(){
        PTO_Request__c pt = new PTO_Request__c();
        pt.Name = 'test1122';
        pt.PTO_start_date__c=Date.newInstance(2019, 10, 27);
        pt.PTO_End_Date__c=Date.newInstance(2019, 11, 2);
        pt.Approval_status__c = 'Approved';
        insert pt;
        
         PTO_Request__c p = new PTO_Request__c();
        p.Name = 'test112233';
        p.PTO_start_date__c=Date.newInstance(2019, 12, 27);
        p.PTO_End_Date__c=Date.newInstance(2020, 11, 2);
        
        insert p;
        //insert pt.Last_PTO_End_Date__c;
       
    }
}